version: '2'
services:
    jupyter-cuda-keras:
        build: .
        image: jupyter-cuda-keras
        devices:
          - "/dev/nvidia0"
          - "/dev/nvidiactl"
          - "/dev/nvidia-uvm"
        volumes:
            - ./volume/jupyter/notebooks:/home/jupyter
            - ./volume/jupyter/config/jupyter_notebook_config.json:/home/jupyter/.jupyter/jupyter_notebook_config.json

